version: '3.8'

services:
  glyph-figma-tool:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FIGMA_ACCESS_TOKEN=${FIGMA_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add a database for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=glyph_figma_tool
  #     - POSTGRES_USER=glyph_user
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: